In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("batsmen_10.csv")

In [4]:
dataset = dataset.fillna(0) #fill empty space with 0
dataset

,name,mt,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,4s,6s,Ct,St,capped
0,Rajesh Bishnoi,First-class,3,5,0,49,25,9.80,168.0,29.16,0,0,8.0,0.0,0,0.0,0
1,Rajesh Bishnoi,List A,10,6,2,34,17,8.50,95.0,35.78,0,0,3.0,0.0,4,0.0,0
2,Rajesh Bishnoi,T20s,1,1,0,1,1,1.00,3.0,33.33,0,0,0.0,0.0,0,0.0,0
3,Chetan Bist,First-class,25,40,3,1137,159,30.72,2391.0,47.55,2,8,142.0,10.0,91,2.0,0
4,Chetan Bist,List A,13,11,2,219,82,24.33,342.0,64.03,0,1,15.0,5.0,15,0.0,0
5,Chetan Bist,T20s,10,6,1,79,41,15.80,68.0,116.17,0,0,5.0,4.0,10,5.0,0
6,robin bist,First-class,99,164,25,6634,220,47.72,14534.0,45.64,15,34,746.0,52.0,47,0.0,0
7,robin bist,List A,51,50,6,1299,109,29.52,1929.0,67.34,1,8,94.0,8.0,24,0.0,0
8,robin bist,T20s,20,18,2,193,30,12.06,232.0,83.18,0,0,13.0,0.0,7,0.0,0
9,Amitkumar Gautam,First-class,19,33,1,1161,159,36.28,2718.0,42.71,4,6,154.0,14.0,13,0.0,0
10,Amitkumar Gautam,List A,12,12,1,293,149,26.63,449.0,65.25,1,1,36.0,4.0,1,0.0,0
11,arjit gupta,First-class,10,19,0,448,77,23.57,878.0,51.02,0,2,67.0,3.0,5,0.0,0
12,arjit gupta,List A,16,15,2,416,107,32.00,503.0,82.70,1,2,35.0,15.0,2,0.0,0
13,arjit gupta,T20s,11,10,1,156,72,17.33,131.0,119.08,0,2,10.0,10.0,2,0.0,0
14,Manendar Singh,First-class,11,20,2,351,63,19.50,949.0,36.98,0,2,57.0,0.0,9,0.0,0
15,Manendar Singh,List A,11,11,1,531,118,53.10,725.0,73.24,2,3,45.0,9.0,9,1.0,0
16,Manendar Singh,T20s,4,4,0,22,12,5.50,34.0,64.70,0,0,1.0,1.0,4,0.0,0
17,Chaitanya Bishnoi,First-class,37,68,5,1706,94,27.07,4459.0,38.25,0,15,204.0,3.0,20,0.0,0
18,Chaitanya Bishnoi,List A,21,21,3,645,88,35.83,1009.0,63.92,0,5,52.0,10.0,4,0.0,0
19,Chaitanya Bishnoi,T20s,14,13,1,211,65,17.58,223.0,94.61,0,1,16.0,5.0,2,0.0,0
20,himanshu rana,First-class,24,43,1,1386,164,33.00,2682.0,51.67,3,8,168.0,5.0,15,0.0,0
21,himanshu rana,List A,14,13,1,406,89,33.83,492.0,82.52,0,2,32.0,7.0,8,0.0,0
22,himanshu rana,T20s,11,10,1,172,59,19.11,144.0,119.44,0,1,18.0,4.0,1,0.0,0
23,Subham rohilla,First-class,22,40,1,964,118,24.71,2046.0,47.11,2,5,113.0,2.0,12,0.0,0
24,Subham rohilla,List A,17,17,1,489,118,30.56,655.0,74.65,1,3,54.0,2.0,4,0.0,0
25,Subham rohilla,T20s,10,10,0,180,44,18.00,187.0,96.25,0,0,23.0,0.0,1,0.0,0
26,rohit sharma,First-class,24,41,2,983,107,25.20,2362.0,41.61,1,7,99.0,2.0,29,3.0,1
27,rohit sharma,List A,11,10,0,188,50,18.80,328.0,57.31,0,1,13.0,1.0,8,0.0,1
28,rohit sharma,T20s,7,6,1,57,22,11.40,58.0,98.27,0,0,6.0,0.0,3,1.0,1
29,manoj tiwari,First-class,114,180,16,8258,267,50.35,14874.0,55.51,26,34,0.0,0.0,120,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Dinesh Karthik,T20s,257,228,41,5107,90,27.31,3855.0,132.47,0,25,505.0,147.0,159,55.0,1
76,Ambati Rayudu,First-class,97,156,21,6151,210,45.56,0.0,0.00,16,34,0.0,0.0,74,0.0,1
77,Ambati Rayudu,List A,151,141,23,4856,124,41.15,0.0,0.00,5,36,0.0,0.0,65,0.0,1
78,Ambati Rayudu,T20s,195,184,24,4235,100,26.46,3362.0,125.96,1,23,360.0,148.0,75,3.0,1
79,Manish Pandey,First-class,87,134,16,6111,238,51.78,9425.0,64.83,19,27,713.0,93.0,124,0.0,1
80,Manish Pandey,List A,139,131,27,4504,117,43.30,4931.0,91.34,8,27,369.0,94.0,68,0.0,1
81,Manish Pandey,T20s,197,182,35,4166,114,28.34,3504.0,118.89,1,20,351.0,112.0,95,2.0,1
82,Mayank Agarwal,First-class,48,81,6,3794,304,50.58,6237.0,60.83,8,22,494.0,40.0,30,0.0,1
83,Mayank Agarwal,List A,75,75,1,3605,176,48.71,3579.0,100.72,12,14,448.0,63.0,28,0.0,1
84,Mayank Agarwal,T20s,111,106,6,2340,111,23.40,1789.0,130.79,1,15,236.0,82.0,38,0.0,1
85,Cheteshwar Pujara,First-class,184,301,35,14474,352,54.41,0.0,0.00,48,49,0.0,0.0,125,0.0,1
86,Cheteshwar Pujara,List A,103,101,19,4445,158,54.20,0.0,0.00,11,29,0.0,0.0,39,0.0,1
87,Cheteshwar Pujara,T20s,58,50,7,1096,81,25.48,1042.0,105.18,0,6,121.0,18.0,30,0.0,1
88,Murali Vijay,First-class,131,220,7,9116,266,42.79,18471.0,49.35,25,38,1112.0,107.0,112,0.0,1
89,Murali Vijay,List A,86,85,2,3360,155,40.48,4206.0,79.88,7,18,323.0,73.0,39,0.0,1
90,Murali Vijay,T20s,154,152,5,3739,127,25.43,3076.0,121.55,2,20,347.0,133.0,62,0.0,1
91,Naman Ojha,First-class,143,244,16,9560,219,41.92,0.0,0.00,21,55,0.0,0.0,417,54.0,0
92,Naman Ojha,List A,133,129,7,3933,167,32.23,0.0,0.00,8,21,0.0,0.0,154,43.0,0
93,Naman Ojha,T20s,170,150,20,2706,94,20.81,2301.0,117.60,0,13,237.0,127.0,107,24.0,0
94,Srikar Bharat,First-class,61,100,6,3433,308,36.52,5921.0,57.98,6,19,434.0,58.0,208,23.0,0
95,Srikar Bharat,List A,46,46,2,1281,125,29.11,1842.0,69.54,3,5,132.0,15.0,52,11.0,0
96,Srikar Bharat,T20s,31,29,2,369,51,13.66,406.0,90.88,0,1,34.0,9.0,27,5.0,0
97,ricky Bhui,First-class,34,52,2,2293,187,45.86,4613.0,49.70,8,10,256.0,36.0,20,0.0,0
98,ricky Bhui,List A,31,29,8,984,103,46.85,1255.0,78.40,1,7,75.0,34.0,13,0.0,0
99,ricky Bhui,T20s,28,28,7,598,73,28.47,504.0,118.65,0,5,44.0,27.0,4,0.0,0
100,Jyothi Sai Krishan,First-class,8,13,1,377,82,31.41,893.0,42.21,0,3,42.0,3.0,4,0.0,0
101,Jyothi Sai Krishan,List A,11,11,1,321,72,32.10,416.0,77.16,0,4,31.0,5.0,3,0.0,0
102,Jyothi Sai Krishan,T20s,12,11,1,151,33,15.10,163.0,92.63,0,0,15.0,0.0,4,0.0,0
103,z,First-class,13,22,2,547,92,27.35,1438.0,38.03,0,4,70.0,0.0,7,0.0,0
104,Himanshu Asnora,T20s,2,2,0,8,6,4.00,13.0,61.53,0,0,0.0,0.0,2,0.0,0

In [5]:
y = dataset.iloc[: , -1]

In [6]:
y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     1
27     1
28     1
29     1
      ..
75     1
76     1
77     1
78     1
79     1
80     1
81     1
82     1
83     1
84     1
85     1
86     1
87     1
88     1
89     1
90     1
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
Name: capped, Length: 105, dtype: int64

In [7]:
X = dataset.iloc[: , 0:16]

In [8]:
X

,name,mt,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,4s,6s,Ct,St
0,Rajesh Bishnoi,First-class,3,5,0,49,25,9.80,168.0,29.16,0,0,8.0,0.0,0,0.0
1,Rajesh Bishnoi,List A,10,6,2,34,17,8.50,95.0,35.78,0,0,3.0,0.0,4,0.0
2,Rajesh Bishnoi,T20s,1,1,0,1,1,1.00,3.0,33.33,0,0,0.0,0.0,0,0.0
3,Chetan Bist,First-class,25,40,3,1137,159,30.72,2391.0,47.55,2,8,142.0,10.0,91,2.0
4,Chetan Bist,List A,13,11,2,219,82,24.33,342.0,64.03,0,1,15.0,5.0,15,0.0
5,Chetan Bist,T20s,10,6,1,79,41,15.80,68.0,116.17,0,0,5.0,4.0,10,5.0
6,robin bist,First-class,99,164,25,6634,220,47.72,14534.0,45.64,15,34,746.0,52.0,47,0.0
7,robin bist,List A,51,50,6,1299,109,29.52,1929.0,67.34,1,8,94.0,8.0,24,0.0
8,robin bist,T20s,20,18,2,193,30,12.06,232.0,83.18,0,0,13.0,0.0,7,0.0
9,Amitkumar Gautam,First-class,19,33,1,1161,159,36.28,2718.0,42.71,4,6,154.0,14.0,13,0.0
10,Amitkumar Gautam,List A,12,12,1,293,149,26.63,449.0,65.25,1,1,36.0,4.0,1,0.0
11,arjit gupta,First-class,10,19,0,448,77,23.57,878.0,51.02,0,2,67.0,3.0,5,0.0
12,arjit gupta,List A,16,15,2,416,107,32.00,503.0,82.70,1,2,35.0,15.0,2,0.0
13,arjit gupta,T20s,11,10,1,156,72,17.33,131.0,119.08,0,2,10.0,10.0,2,0.0
14,Manendar Singh,First-class,11,20,2,351,63,19.50,949.0,36.98,0,2,57.0,0.0,9,0.0
15,Manendar Singh,List A,11,11,1,531,118,53.10,725.0,73.24,2,3,45.0,9.0,9,1.0
16,Manendar Singh,T20s,4,4,0,22,12,5.50,34.0,64.70,0,0,1.0,1.0,4,0.0
17,Chaitanya Bishnoi,First-class,37,68,5,1706,94,27.07,4459.0,38.25,0,15,204.0,3.0,20,0.0
18,Chaitanya Bishnoi,List A,21,21,3,645,88,35.83,1009.0,63.92,0,5,52.0,10.0,4,0.0
19,Chaitanya Bishnoi,T20s,14,13,1,211,65,17.58,223.0,94.61,0,1,16.0,5.0,2,0.0
20,himanshu rana,First-class,24,43,1,1386,164,33.00,2682.0,51.67,3,8,168.0,5.0,15,0.0
21,himanshu rana,List A,14,13,1,406,89,33.83,492.0,82.52,0,2,32.0,7.0,8,0.0
22,himanshu rana,T20s,11,10,1,172,59,19.11,144.0,119.44,0,1,18.0,4.0,1,0.0
23,Subham rohilla,First-class,22,40,1,964,118,24.71,2046.0,47.11,2,5,113.0,2.0,12,0.0
24,Subham rohilla,List A,17,17,1,489,118,30.56,655.0,74.65,1,3,54.0,2.0,4,0.0
25,Subham rohilla,T20s,10,10,0,180,44,18.00,187.0,96.25,0,0,23.0,0.0,1,0.0
26,rohit sharma,First-class,24,41,2,983,107,25.20,2362.0,41.61,1,7,99.0,2.0,29,3.0
27,rohit sharma,List A,11,10,0,188,50,18.80,328.0,57.31,0,1,13.0,1.0,8,0.0
28,rohit sharma,T20s,7,6,1,57,22,11.40,58.0,98.27,0,0,6.0,0.0,3,1.0
29,manoj tiwari,First-class,114,180,16,8258,267,50.35,14874.0,55.51,26,34,0.0,0.0,120,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Dinesh Karthik,T20s,257,228,41,5107,90,27.31,3855.0,132.47,0,25,505.0,147.0,159,55.0
76,Ambati Rayudu,First-class,97,156,21,6151,210,45.56,0.0,0.00,16,34,0.0,0.0,74,0.0
77,Ambati Rayudu,List A,151,141,23,4856,124,41.15,0.0,0.00,5,36,0.0,0.0,65,0.0
78,Ambati Rayudu,T20s,195,184,24,4235,100,26.46,3362.0,125.96,1,23,360.0,148.0,75,3.0
79,Manish Pandey,First-class,87,134,16,6111,238,51.78,9425.0,64.83,19,27,713.0,93.0,124,0.0
80,Manish Pandey,List A,139,131,27,4504,117,43.30,4931.0,91.34,8,27,369.0,94.0,68,0.0
81,Manish Pandey,T20s,197,182,35,4166,114,28.34,3504.0,118.89,1,20,351.0,112.0,95,2.0
82,Mayank Agarwal,First-class,48,81,6,3794,304,50.58,6237.0,60.83,8,22,494.0,40.0,30,0.0
83,Mayank Agarwal,List A,75,75,1,3605,176,48.71,3579.0,100.72,12,14,448.0,63.0,28,0.0
84,Mayank Agarwal,T20s,111,106,6,2340,111,23.40,1789.0,130.79,1,15,236.0,82.0,38,0.0
85,Cheteshwar Pujara,First-class,184,301,35,14474,352,54.41,0.0,0.00,48,49,0.0,0.0,125,0.0
86,Cheteshwar Pujara,List A,103,101,19,4445,158,54.20,0.0,0.00,11,29,0.0,0.0,39,0.0
87,Cheteshwar Pujara,T20s,58,50,7,1096,81,25.48,1042.0,105.18,0,6,121.0,18.0,30,0.0
88,Murali Vijay,First-class,131,220,7,9116,266,42.79,18471.0,49.35,25,38,1112.0,107.0,112,0.0
89,Murali Vijay,List A,86,85,2,3360,155,40.48,4206.0,79.88,7,18,323.0,73.0,39,0.0
90,Murali Vijay,T20s,154,152,5,3739,127,25.43,3076.0,121.55,2,20,347.0,133.0,62,0.0
91,Naman Ojha,First-class,143,244,16,9560,219,41.92,0.0,0.00,21,55,0.0,0.0,417,54.0
92,Naman Ojha,List A,133,129,7,3933,167,32.23,0.0,0.00,8,21,0.0,0.0,154,43.0
93,Naman Ojha,T20s,170,150,20,2706,94,20.81,2301.0,117.60,0,13,237.0,127.0,107,24.0
94,Srikar Bharat,First-class,61,100,6,3433,308,36.52,5921.0,57.98,6,19,434.0,58.0,208,23.0
95,Srikar Bharat,List A,46,46,2,1281,125,29.11,1842.0,69.54,3,5,132.0,15.0,52,11.0
96,Srikar Bharat,T20s,31,29,2,369,51,13.66,406.0,90.88,0,1,34.0,9.0,27,5.0
97,ricky Bhui,First-class,34,52,2,2293,187,45.86,4613.0,49.70,8,10,256.0,36.0,20,0.0
98,ricky Bhui,List A,31,29,8,984,103,46.85,1255.0,78.40,1,7,75.0,34.0,13,0.0
99,ricky Bhui,T20s,28,28,7,598,73,28.47,504.0,118.65,0,5,44.0,27.0,4,0.0
100,Jyothi Sai Krishan,First-class,8,13,1,377,82,31.41,893.0,42.21,0,3,42.0,3.0,4,0.0
101,Jyothi Sai Krishan,List A,11,11,1,321,72,32.10,416.0,77.16,0,4,31.0,5.0,3,0.0
102,Jyothi Sai Krishan,T20s,12,11,1,151,33,15.10,163.0,92.63,0,0,15.0,0.0,4,0.0
103,z,First-class,13,22,2,547,92,27.35,1438.0,38.03,0,4,70.0,0.0,7,0.0
104,Himanshu Asnora,T20s,2,2,0,8,6,4.00,13.0,61.53,0,0,0.0,0.0,2,0.0

In [9]:
name = dataset.iloc[: ,0 ]

name

In [10]:
mt = X.iloc[:,1]
mt

0      First-class
1           List A
2             T20s
3      First-class
4           List A
5             T20s
6      First-class
7           List A
8             T20s
9      First-class
10          List A
11     First-class
12          List A
13            T20s
14     First-class
15          List A
16            T20s
17     First-class
18          List A
19            T20s
20     First-class
21          List A
22            T20s
23     First-class
24          List A
25            T20s
26     First-class
27          List A
28            T20s
29     First-class
          ...
75            T20s
76     First-class
77          List A
78            T20s
79     First-class
80          List A
81            T20s
82     First-class
83          List A
84            T20s
85     First-class
86          List A
87            T20s
88     First-class
89          List A
90            T20s
91     First-class
92          List A
93            T20s
94     First-class
95          List A
96            T20s
97     First-class
98          List A
99            T20s
100    First-class
101         List A
102           T20s
103    First-class
104           T20s
Name: mt, Length: 105, dtype: object

In [11]:

from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
mt_new = labelencoder_x.fit_transform(mt)
X.iloc[:,1]= mt_new

In [12]:
# preprocess :  categorical variable
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
name_new = labelencoder_x.fit_transform(name)
X.iloc[:,0]=name_new

In [13]:
X

,name,mt,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,4s,6s,Ct,St
0,22,0,3,5,0,49,25,9.80,168.0,29.16,0,0,8.0,0.0,0,0.0
1,22,1,10,6,2,34,17,8.50,95.0,35.78,0,0,3.0,0.0,4,0.0
2,22,2,1,1,0,1,1,1.00,3.0,33.33,0,0,0.0,0.0,0,0.0
3,8,0,25,40,3,1137,159,30.72,2391.0,47.55,2,8,142.0,10.0,91,2.0
4,8,1,13,11,2,219,82,24.33,342.0,64.03,0,1,15.0,5.0,15,0.0
5,8,2,10,6,1,79,41,15.80,68.0,116.17,0,0,5.0,4.0,10,5.0
6,32,0,99,164,25,6634,220,47.72,14534.0,45.64,15,34,746.0,52.0,47,0.0
7,32,1,51,50,6,1299,109,29.52,1929.0,67.34,1,8,94.0,8.0,24,0.0
8,32,2,20,18,2,193,30,12.06,232.0,83.18,0,0,13.0,0.0,7,0.0
9,4,0,19,33,1,1161,159,36.28,2718.0,42.71,4,6,154.0,14.0,13,0.0
10,4,1,12,12,1,293,149,26.63,449.0,65.25,1,1,36.0,4.0,1,0.0
11,27,0,10,19,0,448,77,23.57,878.0,51.02,0,2,67.0,3.0,5,0.0
12,27,1,16,15,2,416,107,32.00,503.0,82.70,1,2,35.0,15.0,2,0.0
13,27,2,11,10,1,156,72,17.33,131.0,119.08,0,2,10.0,10.0,2,0.0
14,16,0,11,20,2,351,63,19.50,949.0,36.98,0,2,57.0,0.0,9,0.0
15,16,1,11,11,1,531,118,53.10,725.0,73.24,2,3,45.0,9.0,9,1.0
16,16,2,4,4,0,22,12,5.50,34.0,64.70,0,0,1.0,1.0,4,0.0
17,7,0,37,68,5,1706,94,27.07,4459.0,38.25,0,15,204.0,3.0,20,0.0
18,7,1,21,21,3,645,88,35.83,1009.0,63.92,0,5,52.0,10.0,4,0.0
19,7,2,14,13,1,211,65,17.58,223.0,94.61,0,1,16.0,5.0,2,0.0
20,29,0,24,43,1,1386,164,33.00,2682.0,51.67,3,8,168.0,5.0,15,0.0
21,29,1,14,13,1,406,89,33.83,492.0,82.52,0,2,32.0,7.0,8,0.0
22,29,2,11,10,1,172,59,19.11,144.0,119.44,0,1,18.0,4.0,1,0.0
23,25,0,22,40,1,964,118,24.71,2046.0,47.11,2,5,113.0,2.0,12,0.0
24,25,1,17,17,1,489,118,30.56,655.0,74.65,1,3,54.0,2.0,4,0.0
25,25,2,10,10,0,180,44,18.00,187.0,96.25,0,0,23.0,0.0,1,0.0
26,33,0,24,41,2,983,107,25.20,2362.0,41.61,1,7,99.0,2.0,29,3.0
27,33,1,11,10,0,188,50,18.80,328.0,57.31,0,1,13.0,1.0,8,0.0
28,33,2,7,6,1,57,22,11.40,58.0,98.27,0,0,6.0,0.0,3,1.0
29,30,0,114,180,16,8258,267,50.35,14874.0,55.51,26,34,0.0,0.0,120,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,10,2,257,228,41,5107,90,27.31,3855.0,132.47,0,25,505.0,147.0,159,55.0
76,3,0,97,156,21,6151,210,45.56,0.0,0.00,16,34,0.0,0.0,74,0.0
77,3,1,151,141,23,4856,124,41.15,0.0,0.00,5,36,0.0,0.0,65,0.0
78,3,2,195,184,24,4235,100,26.46,3362.0,125.96,1,23,360.0,148.0,75,3.0
79,17,0,87,134,16,6111,238,51.78,9425.0,64.83,19,27,713.0,93.0,124,0.0
80,17,1,139,131,27,4504,117,43.30,4931.0,91.34,8,27,369.0,94.0,68,0.0
81,17,2,197,182,35,4166,114,28.34,3504.0,118.89,1,20,351.0,112.0,95,2.0
82,18,0,48,81,6,3794,304,50.58,6237.0,60.83,8,22,494.0,40.0,30,0.0
83,18,1,75,75,1,3605,176,48.71,3579.0,100.72,12,14,448.0,63.0,28,0.0
84,18,2,111,106,6,2340,111,23.40,1789.0,130.79,1,15,236.0,82.0,38,0.0
85,9,0,184,301,35,14474,352,54.41,0.0,0.00,48,49,0.0,0.0,125,0.0
86,9,1,103,101,19,4445,158,54.20,0.0,0.00,11,29,0.0,0.0,39,0.0
87,9,2,58,50,7,1096,81,25.48,1042.0,105.18,0,6,121.0,18.0,30,0.0
88,19,0,131,220,7,9116,266,42.79,18471.0,49.35,25,38,1112.0,107.0,112,0.0
89,19,1,86,85,2,3360,155,40.48,4206.0,79.88,7,18,323.0,73.0,39,0.0
90,19,2,154,152,5,3739,127,25.43,3076.0,121.55,2,20,347.0,133.0,62,0.0
91,20,0,143,244,16,9560,219,41.92,0.0,0.00,21,55,0.0,0.0,417,54.0
92,20,1,133,129,7,3933,167,32.23,0.0,0.00,8,21,0.0,0.0,154,43.0
93,20,2,170,150,20,2706,94,20.81,2301.0,117.60,0,13,237.0,127.0,107,24.0
94,24,0,61,100,6,3433,308,36.52,5921.0,57.98,6,19,434.0,58.0,208,23.0
95,24,1,46,46,2,1281,125,29.11,1842.0,69.54,3,5,132.0,15.0,52,11.0
96,24,2,31,29,2,369,51,13.66,406.0,90.88,0,1,34.0,9.0,27,5.0
97,31,0,34,52,2,2293,187,45.86,4613.0,49.70,8,10,256.0,36.0,20,0.0
98,31,1,31,29,8,984,103,46.85,1255.0,78.40,1,7,75.0,34.0,13,0.0
99,31,2,28,28,7,598,73,28.47,504.0,118.65,0,5,44.0,27.0,4,0.0
100,13,0,8,13,1,377,82,31.41,893.0,42.21,0,3,42.0,3.0,4,0.0
101,13,1,11,11,1,321,72,32.10,416.0,77.16,0,4,31.0,5.0,3,0.0
102,13,2,12,11,1,151,33,15.10,163.0,92.63,0,0,15.0,0.0,4,0.0
103,36,0,13,22,2,547,92,27.35,1438.0,38.03,0,4,70.0,0.0,7,0.0
104,12,2,2,2,0,8,6,4.00,13.0,61.53,0,0,0.0,0.0,2,0.0

In [14]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()

In [15]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [16]:
dataset.iloc[:,1]=mt_new 
mt_new

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 2], dtype=int64)

In [17]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder( categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [18]:
X

array([[ 1.,  0.,  1., ...,  0.,  0.,  0.],
       [ 1.,  0.,  1., ...,  0.,  4.,  0.],
       [ 1.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 1.,  0.,  1., ...,  0.,  4.,  0.],
       [ 1.,  0.,  1., ...,  0.,  7.,  0.],
       [ 1.,  0.,  1., ...,  0.,  2.,  0.]])

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [21]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [22]:
model.fit(X_train ,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
model.predict(X_test)

array([  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
         1.00000000e+00,   1.00000000e+00,   3.84473009e-12,
         4.84338990e-01,   1.06920028e-12,  -2.70308775e-12,
         2.51010324e-12,  -1.02182152e-12,   1.00000000e+00,
         1.00000000e+00,  -1.20603527e-12,   1.00000000e+00,
        -4.52596294e-12,   1.00000000e+00,  -4.07110456e-12,
        -7.28583860e-13,   1.00000000e+00,   1.26451627e-12])

In [24]:
y_test

30     1
65     1
64     1
53     1
45     1
94     0
104    0
47     0
10     0
0      0
18     0
31     0
89     1
96     0
77     1
4      0
80     1
33     0
12     0
26     1
99     0
Name: capped, dtype: int64

In [26]:
dataset = pd.read_csv("bowler_1.csv")

In [27]:
dataset = dataset.fillna(0)
dataset

,name,mt,Mat,Inns,Balls,Runs,Wkts,Ave,Econ,SR,4w,5w,10,capped
0,Praveen Kumar,First-class,66,121.0,14158,6306,267,23.61,2.67,53.0,16.0,17.0,1,1
1,Praveen Kumar,List A,139,0.0,6730,5336,185,28.84,4.75,36.3,4.0,2.0,0,1
2,Praveen Kumar,T20s,177,177.0,3695,4599,143,32.16,7.46,25.8,0.0,0.0,0,1
3,Akshdeep Nath,First-class,22,12.0,366,179,6,29.83,2.93,61.0,0.0,0.0,0,0
4,Akshdeep Nath,List A,44,14.0,360,327,13,25.15,5.45,27.6,0.0,0.0,0,0
5,Akshdeep Nath,T20s,51,15.0,177,241,12,20.08,8.16,14.7,0.0,0.0,0,0
6,Amit Mishra,First-class,152,0.0,30843,15608,535,29.17,3.03,57.6,0.0,21.0,1,1
7,Amit Mishra,List A,144,0.0,7426,5681,242,23.47,4.59,30.6,7.0,6.0,0,1
8,Amit Mishra,T20s,199,198.0,4168,4970,228,21.79,7.15,18.2,4.0,2.0,0,1
9,Piyush Chawla,First-class,130,227.0,26086,14276,437,32.66,3.28,59.6,22.0,23.0,3,1
10,Piyush Chawla,List A,131,127.0,6487,5363,208,25.78,4.96,31.1,7.0,3.0,0,1
11,Piyush Chawla,T20s,208,207.0,4290,5379,218,24.67,7.52,19.6,3.0,0.0,0,0
12,Mohammad Saif,First-class,17,18.0,451,252,3,84.00,3.35,150.3,0.0,0.0,0,0
13,Mohammad Saif,List A,5,4.0,150,174,3,58.00,6.96,50.0,0.0,0.0,0,0
14,Ankit Rajpoot,First-class,50,89.0,9429,4761,174,27.36,3.02,54.1,9.0,8.0,1,0
15,Ankit Rajpoot,List A,30,29.0,1421,1152,36,32.00,4.86,39.4,0.0,0.0,0,0
16,Ankit Rajpoot,T20s,54,54.0,1078,1351,68,19.86,7.51,15.8,1.0,2.0,0,0
17,Kuldeep Yadav,First-class,30,49.0,5774,3512,117,30.01,3.64,49.3,7.0,6.0,0,1
18,Kuldeep Yadav,List A,45,43.0,2334,1843,83,22.20,4.73,28.1,2.0,2.0,0,1
19,Kuldeep Yadav,T20s,79,78.0,1695,2073,106,19.55,7.33,15.9,3.0,2.0,0,1
20,Deependra Pandey,List A,1,1.0,42,36,0,0.00,5.14,0.0,0.0,0.0,0,0
21,Deependra Pandey,T20s,1,1.0,6,9,0,0.00,9.00,0.0,0.0,0.0,0,0
22,JaydevUnadkat,First-class,73,125.0,12392,6172,233,26.48,2.98,53.1,11.0,12.0,2,1
23,JaydevUnadkat,List A,84,84.0,4416,3549,116,30.59,4.82,38.0,5.0,1.0,0,1
24,JaydevUnadkat,T20s,110,109.0,2331,3054,134,22.79,7.86,17.3,0.0,2.0,0,1
25,Hardik Rathod,First-class,18,29.0,2942,1508,38,39.68,3.07,77.4,0.0,1.0,0,0
26,Hardik Rathod,List A,3,3.0,78,76,0,0.00,5.84,0.0,0.0,0.0,0,0
27,Hardik Rathod,T20s,5,5.0,106,141,2,70.50,7.98,53.0,0.0,0.0,0,0
28,Dhawal Kulkarni,First-class,86,140.0,15531,7174,261,27.48,2.77,59.5,9.0,15.0,1,1
29,Dhawal Kulkarni,List A,110,109.0,5461,4308,187,23.03,4.73,29.2,5.0,3.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,jayant yadav,T20s,40,36.0,700,695,20,34.75,5.95,35.0,0.0,0.0,0,0
115,tinu kundu,First-class,4,7.0,799,317,24,13.20,2.38,33.2,1.0,2.0,1,0
116,ashok dinda,First-class,115,194.0,22866,11823,417,28.35,3.10,54.8,19.0,26.0,5,1
117,ashok dinda,List A,92,92.0,4686,4015,141,28.47,5.14,33.2,2.0,3.0,0,1
118,ashok dinda,T20s,133,130.0,2695,3441,132,26.06,7.66,20.4,3.0,0.0,0,1
119,mukesh kumar,First-class,12,22.0,2170,1045,48,21.77,2.88,45.2,3.0,2.0,0,0
120,mukesh kumar,List A,8,8.0,384,325,5,65.00,5.07,76.8,0.0,0.0,0,0
121,mukesh kumar,T20s,6,6.0,126,145,6,24.16,6.90,21.0,0.0,0.0,0,0
122,pradipta pramika,First-class,7,12.0,1275,614,25,24.56,2.88,51.0,2.0,0.0,0,0
123,pradipta pramika,List A,8,8.0,384,296,12,24.66,4.62,32.0,1.0,0.0,0,0
124,pradipta pramika,T20s,1,1.0,12,24,0,0.00,12.00,0.0,0.0,0.0,0,0
125,ishan porel,First-class,12,18.0,1909,906,32,28.31,2.84,59.6,2.0,2.0,0,0
126,ishan porel,List A,9,9.0,366,296,12,24.66,4.85,30.5,1.0,0.0,0,0
127,prayas ray barman,List A,9,9.0,341,253,11,23.00,4.45,31.0,1.0,0.0,0,0
128,shahbaz ahmed,First-class,2,3.0,180,80,2,40.00,2.66,90.0,0.0,0.0,0,0
129,shahbaz ahmed,List A,6,6.0,210,160,6,26.66,4.57,35.0,0.0,0.0,0,0
130,bandaru ayyappa,First-class,29,48.0,5175,2566,77,33.32,2.97,67.2,3.0,3.0,0,0
131,bandaru ayyappa,List A,31,31.0,1620,1337,43,31.09,4.95,37.6,1.0,0.0,0,0
132,bandaru ayyappa,T20s,26,26.0,557,667,31,21.51,7.18,17.9,0.0,0.0,0,0
133,karthik Raman,First-class,4,6.0,462,255,9,28.33,3.31,51.3,0.0,0.0,0,0
134,karthik Raman,List A,8,8.0,361,313,14,22.35,5.20,25.7,2.0,0.0,0,0
135,karthik Raman,T20s,3,1.0,12,23,0,0.00,11.50,0.0,0.0,0.0,0,0
136,karn sharma,First-class,69,107.0,10155,5381,188,28.62,3.17,54.0,8.0,10.0,1,0
137,karn sharma,List A,80,75.0,3805,3001,99,30.31,4.73,38.4,0.0,2.0,0,0
138,karn sharma,T20s,119,109.0,2027,2483,101,24.58,7.34,20.0,2.0,1.0,0,0
139,Paisikalva Vijaykumar,First-class,69,118.0,14608,5386,239,22.53,2.21,61.1,10.0,10.0,1,0
140,Paisikalva Vijaykumar,List A,28,28.0,1448,1034,34,30.41,4.28,42.5,1.0,0.0,0,0
141,Paisikalva Vijaykumar,T20s,18,18.0,342,466,10,46.60,8.17,34.2,0.0,0.0,0,0
142,Prithvi Raj,First-class,6,11.0,1036,512,21,24.38,2.96,49.3,1.0,0.0,0,0
143,Prithvi Raj,List A,1,1.0,60,65,2,32.50,6.50,30.0,0.0,0.0,0,0

In [28]:
y = dataset.iloc[: , -1]

In [29]:
y

0      1
1      1
2      1
3      0
4      0
5      0
6      1
7      1
8      1
9      1
10     1
11     0
12     0
13     0
14     0
15     0
16     0
17     1
18     1
19     1
20     0
21     0
22     1
23     1
24     1
25     0
26     0
27     0
28     1
29     1
      ..
114    0
115    0
116    1
117    1
118    1
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
Name: capped, Length: 144, dtype: int64

In [30]:
X = dataset.iloc[: , 0:13]

In [31]:
X

,name,mt,Mat,Inns,Balls,Runs,Wkts,Ave,Econ,SR,4w,5w,10
0,Praveen Kumar,First-class,66,121.0,14158,6306,267,23.61,2.67,53.0,16.0,17.0,1
1,Praveen Kumar,List A,139,0.0,6730,5336,185,28.84,4.75,36.3,4.0,2.0,0
2,Praveen Kumar,T20s,177,177.0,3695,4599,143,32.16,7.46,25.8,0.0,0.0,0
3,Akshdeep Nath,First-class,22,12.0,366,179,6,29.83,2.93,61.0,0.0,0.0,0
4,Akshdeep Nath,List A,44,14.0,360,327,13,25.15,5.45,27.6,0.0,0.0,0
5,Akshdeep Nath,T20s,51,15.0,177,241,12,20.08,8.16,14.7,0.0,0.0,0
6,Amit Mishra,First-class,152,0.0,30843,15608,535,29.17,3.03,57.6,0.0,21.0,1
7,Amit Mishra,List A,144,0.0,7426,5681,242,23.47,4.59,30.6,7.0,6.0,0
8,Amit Mishra,T20s,199,198.0,4168,4970,228,21.79,7.15,18.2,4.0,2.0,0
9,Piyush Chawla,First-class,130,227.0,26086,14276,437,32.66,3.28,59.6,22.0,23.0,3
10,Piyush Chawla,List A,131,127.0,6487,5363,208,25.78,4.96,31.1,7.0,3.0,0
11,Piyush Chawla,T20s,208,207.0,4290,5379,218,24.67,7.52,19.6,3.0,0.0,0
12,Mohammad Saif,First-class,17,18.0,451,252,3,84.00,3.35,150.3,0.0,0.0,0
13,Mohammad Saif,List A,5,4.0,150,174,3,58.00,6.96,50.0,0.0,0.0,0
14,Ankit Rajpoot,First-class,50,89.0,9429,4761,174,27.36,3.02,54.1,9.0,8.0,1
15,Ankit Rajpoot,List A,30,29.0,1421,1152,36,32.00,4.86,39.4,0.0,0.0,0
16,Ankit Rajpoot,T20s,54,54.0,1078,1351,68,19.86,7.51,15.8,1.0,2.0,0
17,Kuldeep Yadav,First-class,30,49.0,5774,3512,117,30.01,3.64,49.3,7.0,6.0,0
18,Kuldeep Yadav,List A,45,43.0,2334,1843,83,22.20,4.73,28.1,2.0,2.0,0
19,Kuldeep Yadav,T20s,79,78.0,1695,2073,106,19.55,7.33,15.9,3.0,2.0,0
20,Deependra Pandey,List A,1,1.0,42,36,0,0.00,5.14,0.0,0.0,0.0,0
21,Deependra Pandey,T20s,1,1.0,6,9,0,0.00,9.00,0.0,0.0,0.0,0
22,JaydevUnadkat,First-class,73,125.0,12392,6172,233,26.48,2.98,53.1,11.0,12.0,2
23,JaydevUnadkat,List A,84,84.0,4416,3549,116,30.59,4.82,38.0,5.0,1.0,0
24,JaydevUnadkat,T20s,110,109.0,2331,3054,134,22.79,7.86,17.3,0.0,2.0,0
25,Hardik Rathod,First-class,18,29.0,2942,1508,38,39.68,3.07,77.4,0.0,1.0,0
26,Hardik Rathod,List A,3,3.0,78,76,0,0.00,5.84,0.0,0.0,0.0,0
27,Hardik Rathod,T20s,5,5.0,106,141,2,70.50,7.98,53.0,0.0,0.0,0
28,Dhawal Kulkarni,First-class,86,140.0,15531,7174,261,27.48,2.77,59.5,9.0,15.0,1
29,Dhawal Kulkarni,List A,110,109.0,5461,4308,187,23.03,4.73,29.2,5.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,jayant yadav,T20s,40,36.0,700,695,20,34.75,5.95,35.0,0.0,0.0,0
115,tinu kundu,First-class,4,7.0,799,317,24,13.20,2.38,33.2,1.0,2.0,1
116,ashok dinda,First-class,115,194.0,22866,11823,417,28.35,3.10,54.8,19.0,26.0,5
117,ashok dinda,List A,92,92.0,4686,4015,141,28.47,5.14,33.2,2.0,3.0,0
118,ashok dinda,T20s,133,130.0,2695,3441,132,26.06,7.66,20.4,3.0,0.0,0
119,mukesh kumar,First-class,12,22.0,2170,1045,48,21.77,2.88,45.2,3.0,2.0,0
120,mukesh kumar,List A,8,8.0,384,325,5,65.00,5.07,76.8,0.0,0.0,0
121,mukesh kumar,T20s,6,6.0,126,145,6,24.16,6.90,21.0,0.0,0.0,0
122,pradipta pramika,First-class,7,12.0,1275,614,25,24.56,2.88,51.0,2.0,0.0,0
123,pradipta pramika,List A,8,8.0,384,296,12,24.66,4.62,32.0,1.0,0.0,0
124,pradipta pramika,T20s,1,1.0,12,24,0,0.00,12.00,0.0,0.0,0.0,0
125,ishan porel,First-class,12,18.0,1909,906,32,28.31,2.84,59.6,2.0,2.0,0
126,ishan porel,List A,9,9.0,366,296,12,24.66,4.85,30.5,1.0,0.0,0
127,prayas ray barman,List A,9,9.0,341,253,11,23.00,4.45,31.0,1.0,0.0,0
128,shahbaz ahmed,First-class,2,3.0,180,80,2,40.00,2.66,90.0,0.0,0.0,0
129,shahbaz ahmed,List A,6,6.0,210,160,6,26.66,4.57,35.0,0.0,0.0,0
130,bandaru ayyappa,First-class,29,48.0,5175,2566,77,33.32,2.97,67.2,3.0,3.0,0
131,bandaru ayyappa,List A,31,31.0,1620,1337,43,31.09,4.95,37.6,1.0,0.0,0
132,bandaru ayyappa,T20s,26,26.0,557,667,31,21.51,7.18,17.9,0.0,0.0,0
133,karthik Raman,First-class,4,6.0,462,255,9,28.33,3.31,51.3,0.0,0.0,0
134,karthik Raman,List A,8,8.0,361,313,14,22.35,5.20,25.7,2.0,0.0,0
135,karthik Raman,T20s,3,1.0,12,23,0,0.00,11.50,0.0,0.0,0.0,0
136,karn sharma,First-class,69,107.0,10155,5381,188,28.62,3.17,54.0,8.0,10.0,1
137,karn sharma,List A,80,75.0,3805,3001,99,30.31,4.73,38.4,0.0,2.0,0
138,karn sharma,T20s,119,109.0,2027,2483,101,24.58,7.34,20.0,2.0,1.0,0
139,Paisikalva Vijaykumar,First-class,69,118.0,14608,5386,239,22.53,2.21,61.1,10.0,10.0,1
140,Paisikalva Vijaykumar,List A,28,28.0,1448,1034,34,30.41,4.28,42.5,1.0,0.0,0
141,Paisikalva Vijaykumar,T20s,18,18.0,342,466,10,46.60,8.17,34.2,0.0,0.0,0
142,Prithvi Raj,First-class,6,11.0,1036,512,21,24.38,2.96,49.3,1.0,0.0,0
143,Prithvi Raj,List A,1,1.0,60,65,2,32.50,6.50,30.0,0.0,0.0,0

In [33]:
name = dataset.iloc[: ,0 ]

In [34]:
mt = X.iloc[:,1]
mt

0      First-class
1           List A
2             T20s
3      First-class
4           List A
5             T20s
6      First-class
7           List A
8             T20s
9      First-class
10          List A
11            T20s
12     First-class
13          List A
14     First-class
15          List A
16            T20s
17     First-class
18          List A
19            T20s
20          List A
21            T20s
22     First-class
23          List A
24            T20s
25     First-class
26          List A
27            T20s
28     First-class
29          List A
          ...
114           T20s
115    First-class
116    First-class
117         List A
118           T20s
119    First-class
120         List A
121           T20s
122    First-class
123         List A
124           T20s
125    First-class
126         List A
127         List A
128    First-class
129         List A
130    First-class
131         List A
132           T20s
133    First-class
134         List A
135           T20s
136    First-class
137         List A
138           T20s
139    First-class
140         List A
141           T20s
142    First-class
143         List A
Name: mt, Length: 144, dtype: object

In [35]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
mt_new = labelencoder_x.fit_transform(mt)
X.iloc[:,1]= mt_new

In [36]:
# preprocess :  categorical variable
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
name_new = labelencoder_x.fit_transform(name)
X.iloc[:,0]=name_new

In [37]:
X

,name,mt,Mat,Inns,Balls,Runs,Wkts,Ave,Econ,SR,4w,5w,10
0,19,0,66,121.0,14158,6306,267,23.61,2.67,53.0,16.0,17.0,1
1,19,1,139,0.0,6730,5336,185,28.84,4.75,36.3,4.0,2.0,0
2,19,2,177,177.0,3695,4599,143,32.16,7.46,25.8,0.0,0.0,0
3,0,0,22,12.0,366,179,6,29.83,2.93,61.0,0.0,0.0,0
4,0,1,44,14.0,360,327,13,25.15,5.45,27.6,0.0,0.0,0
5,0,2,51,15.0,177,241,12,20.08,8.16,14.7,0.0,0.0,0
6,1,0,152,0.0,30843,15608,535,29.17,3.03,57.6,0.0,21.0,1
7,1,1,144,0.0,7426,5681,242,23.47,4.59,30.6,7.0,6.0,0
8,1,2,199,198.0,4168,4970,228,21.79,7.15,18.2,4.0,2.0,0
9,17,0,130,227.0,26086,14276,437,32.66,3.28,59.6,22.0,23.0,3
10,17,1,131,127.0,6487,5363,208,25.78,4.96,31.1,7.0,3.0,0
11,17,2,208,207.0,4290,5379,218,24.67,7.52,19.6,3.0,0.0,0
12,14,0,17,18.0,451,252,3,84.00,3.35,150.3,0.0,0.0,0
13,14,1,5,4.0,150,174,3,58.00,6.96,50.0,0.0,0.0,0
14,2,0,50,89.0,9429,4761,174,27.36,3.02,54.1,9.0,8.0,1
15,2,1,30,29.0,1421,1152,36,32.00,4.86,39.4,0.0,0.0,0
16,2,2,54,54.0,1078,1351,68,19.86,7.51,15.8,1.0,2.0,0
17,12,0,30,49.0,5774,3512,117,30.01,3.64,49.3,7.0,6.0,0
18,12,1,45,43.0,2334,1843,83,22.20,4.73,28.1,2.0,2.0,0
19,12,2,79,78.0,1695,2073,106,19.55,7.33,15.9,3.0,2.0,0
20,3,1,1,1.0,42,36,0,0.00,5.14,0.0,0.0,0.0,0
21,3,2,1,1.0,6,9,0,0.00,9.00,0.0,0.0,0.0,0
22,10,0,73,125.0,12392,6172,233,26.48,2.98,53.1,11.0,12.0,2
23,10,1,84,84.0,4416,3549,116,30.59,4.82,38.0,5.0,1.0,0
24,10,2,110,109.0,2331,3054,134,22.79,7.86,17.3,0.0,2.0,0
25,6,0,18,29.0,2942,1508,38,39.68,3.07,77.4,0.0,1.0,0
26,6,1,3,3.0,78,76,0,0.00,5.84,0.0,0.0,0.0,0
27,6,2,5,5.0,106,141,2,70.50,7.98,53.0,0.0,0.0,0
28,4,0,86,140.0,15531,7174,261,27.48,2.77,59.5,9.0,15.0,1
29,4,1,110,109.0,5461,4308,187,23.03,4.73,29.2,5.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,39,2,40,36.0,700,695,20,34.75,5.95,35.0,0.0,0.0,0
115,48,0,4,7.0,799,317,24,13.20,2.38,33.2,1.0,2.0,1
116,33,0,115,194.0,22866,11823,417,28.35,3.10,54.8,19.0,26.0,5
117,33,1,92,92.0,4686,4015,141,28.47,5.14,33.2,2.0,3.0,0
118,33,2,133,130.0,2695,3441,132,26.06,7.66,20.4,3.0,0.0,0
119,43,0,12,22.0,2170,1045,48,21.77,2.88,45.2,3.0,2.0,0
120,43,1,8,8.0,384,325,5,65.00,5.07,76.8,0.0,0.0,0
121,43,2,6,6.0,126,145,6,24.16,6.90,21.0,0.0,0.0,0
122,44,0,7,12.0,1275,614,25,24.56,2.88,51.0,2.0,0.0,0
123,44,1,8,8.0,384,296,12,24.66,4.62,32.0,1.0,0.0,0
124,44,2,1,1.0,12,24,0,0.00,12.00,0.0,0.0,0.0,0
125,37,0,12,18.0,1909,906,32,28.31,2.84,59.6,2.0,2.0,0
126,37,1,9,9.0,366,296,12,24.66,4.85,30.5,1.0,0.0,0
127,45,1,9,9.0,341,253,11,23.00,4.45,31.0,1.0,0.0,0
128,47,0,2,3.0,180,80,2,40.00,2.66,90.0,0.0,0.0,0
129,47,1,6,6.0,210,160,6,26.66,4.57,35.0,0.0,0.0,0
130,34,0,29,48.0,5175,2566,77,33.32,2.97,67.2,3.0,3.0,0
131,34,1,31,31.0,1620,1337,43,31.09,4.95,37.6,1.0,0.0,0
132,34,2,26,26.0,557,667,31,21.51,7.18,17.9,0.0,0.0,0
133,41,0,4,6.0,462,255,9,28.33,3.31,51.3,0.0,0.0,0
134,41,1,8,8.0,361,313,14,22.35,5.20,25.7,2.0,0.0,0
135,41,2,3,1.0,12,23,0,0.00,11.50,0.0,0.0,0.0,0
136,40,0,69,107.0,10155,5381,188,28.62,3.17,54.0,8.0,10.0,1
137,40,1,80,75.0,3805,3001,99,30.31,4.73,38.4,0.0,2.0,0
138,40,2,119,109.0,2027,2483,101,24.58,7.34,20.0,2.0,1.0,0
139,16,0,69,118.0,14608,5386,239,22.53,2.21,61.1,10.0,10.0,1
140,16,1,28,28.0,1448,1034,34,30.41,4.28,42.5,1.0,0.0,0
141,16,2,18,18.0,342,466,10,46.60,8.17,34.2,0.0,0.0,0
142,20,0,6,11.0,1036,512,21,24.38,2.96,49.3,1.0,0.0,0
143,20,1,1,1.0,60,65,2,32.50,6.50,30.0,0.0,0.0,0

In [38]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()

In [39]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [40]:
dataset.iloc[:,1]=mt_new 
mt_new

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1], dtype=int64)

In [41]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder( categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [42]:
X

array([[  1.,   0.,   1., ...,  16.,  17.,   1.],
       [  1.,   0.,   1., ...,   4.,   2.,   0.],
       [  1.,   0.,   1., ...,   0.,   0.,   0.],
       ...,
       [  1.,   0.,   1., ...,   0.,   0.,   0.],
       [  1.,   0.,   1., ...,   1.,   0.,   0.],
       [  1.,   0.,   1., ...,   0.,   0.,   0.]])

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [45]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [46]:
model.fit(X_train ,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [47]:
model.predict(X_test)

array([  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
         1.00000000e+00,   1.00000000e+00,   2.35378383e-12,
         2.74391621e-12,   4.85918286e-01,   4.85918286e-01,
         1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
         1.85862437e-12,  -1.18083321e-12,   9.29589739e-13,
         4.85918286e-01,   1.94211314e-12,   1.00000000e+00,
         1.13287157e-12,   1.00000000e+00,   1.00000000e+00,
         5.48783241e-13,   1.00000000e+00,   1.94744221e-12,
         1.00000000e+00,   1.89082083e-12,   1.00000000e+00,
         8.35664871e-13,   2.05646611e-12])

In [48]:
y_test

117    1
19     1
82     1
97     1
56     1
12     0
132    0
65     1
66     1
18     1
51     1
78     1
94     0
133    0
100    0
64     1
27     0
69     1
125    0
73     1
11     0
119    0
110    1
113    0
55     1
45     0
9      1
4      0
26     0
Name: capped, dtype: int64