In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("bowler_1.csv")

In [3]:
dataset = dataset.fillna(0)
dataset

,name,mt,Mat,Inns,Balls,Runs,Wkts,Ave,Econ,SR,4w,5w,10,capped
0,Praveen Kumar,First-class,66,121.0,14158,6306,267,23.61,2.67,53.0,16.0,17.0,1,1
1,Praveen Kumar,List A,139,0.0,6730,5336,185,28.84,4.75,36.3,4.0,2.0,0,1
2,Praveen Kumar,T20s,177,177.0,3695,4599,143,32.16,7.46,25.8,0.0,0.0,0,1
3,Akshdeep Nath,First-class,22,12.0,366,179,6,29.83,2.93,61.0,0.0,0.0,0,0
4,Akshdeep Nath,List A,44,14.0,360,327,13,25.15,5.45,27.6,0.0,0.0,0,0
5,Akshdeep Nath,T20s,51,15.0,177,241,12,20.08,8.16,14.7,0.0,0.0,0,0
6,Amit Mishra,First-class,152,0.0,30843,15608,535,29.17,3.03,57.6,0.0,21.0,1,1
7,Amit Mishra,List A,144,0.0,7426,5681,242,23.47,4.59,30.6,7.0,6.0,0,1
8,Amit Mishra,T20s,199,198.0,4168,4970,228,21.79,7.15,18.2,4.0,2.0,0,1
9,Piyush Chawla,First-class,130,227.0,26086,14276,437,32.66,3.28,59.6,22.0,23.0,3,1
10,Piyush Chawla,List A,131,127.0,6487,5363,208,25.78,4.96,31.1,7.0,3.0,0,1
11,Piyush Chawla,T20s,208,207.0,4290,5379,218,24.67,7.52,19.6,3.0,0.0,0,0
12,Mohammad Saif,First-class,17,18.0,451,252,3,84.00,3.35,150.3,0.0,0.0,0,0
13,Mohammad Saif,List A,5,4.0,150,174,3,58.00,6.96,50.0,0.0,0.0,0,0
14,Ankit Rajpoot,First-class,50,89.0,9429,4761,174,27.36,3.02,54.1,9.0,8.0,1,0
15,Ankit Rajpoot,List A,30,29.0,1421,1152,36,32.00,4.86,39.4,0.0,0.0,0,0
16,Ankit Rajpoot,T20s,54,54.0,1078,1351,68,19.86,7.51,15.8,1.0,2.0,0,0
17,Kuldeep Yadav,First-class,30,49.0,5774,3512,117,30.01,3.64,49.3,7.0,6.0,0,1
18,Kuldeep Yadav,List A,45,43.0,2334,1843,83,22.20,4.73,28.1,2.0,2.0,0,1
19,Kuldeep Yadav,T20s,79,78.0,1695,2073,106,19.55,7.33,15.9,3.0,2.0,0,1
20,Deependra Pandey,List A,1,1.0,42,36,0,0.00,5.14,0.0,0.0,0.0,0,0
21,Deependra Pandey,T20s,1,1.0,6,9,0,0.00,9.00,0.0,0.0,0.0,0,0
22,JaydevUnadkat,First-class,73,125.0,12392,6172,233,26.48,2.98,53.1,11.0,12.0,2,1
23,JaydevUnadkat,List A,84,84.0,4416,3549,116,30.59,4.82,38.0,5.0,1.0,0,1
24,JaydevUnadkat,T20s,110,109.0,2331,3054,134,22.79,7.86,17.3,0.0,2.0,0,1
25,Hardik Rathod,First-class,18,29.0,2942,1508,38,39.68,3.07,77.4,0.0,1.0,0,0
26,Hardik Rathod,List A,3,3.0,78,76,0,0.00,5.84,0.0,0.0,0.0,0,0
27,Hardik Rathod,T20s,5,5.0,106,141,2,70.50,7.98,53.0,0.0,0.0,0,0
28,Dhawal Kulkarni,First-class,86,140.0,15531,7174,261,27.48,2.77,59.5,9.0,15.0,1,1
29,Dhawal Kulkarni,List A,110,109.0,5461,4308,187,23.03,4.73,29.2,5.0,3.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,jayant yadav,T20s,40,36.0,700,695,20,34.75,5.95,35.0,0.0,0.0,0,0
115,tinu kundu,First-class,4,7.0,799,317,24,13.20,2.38,33.2,1.0,2.0,1,0
116,ashok dinda,First-class,115,194.0,22866,11823,417,28.35,3.10,54.8,19.0,26.0,5,1
117,ashok dinda,List A,92,92.0,4686,4015,141,28.47,5.14,33.2,2.0,3.0,0,1
118,ashok dinda,T20s,133,130.0,2695,3441,132,26.06,7.66,20.4,3.0,0.0,0,1
119,mukesh kumar,First-class,12,22.0,2170,1045,48,21.77,2.88,45.2,3.0,2.0,0,0
120,mukesh kumar,List A,8,8.0,384,325,5,65.00,5.07,76.8,0.0,0.0,0,0
121,mukesh kumar,T20s,6,6.0,126,145,6,24.16,6.90,21.0,0.0,0.0,0,0
122,pradipta pramika,First-class,7,12.0,1275,614,25,24.56,2.88,51.0,2.0,0.0,0,0
123,pradipta pramika,List A,8,8.0,384,296,12,24.66,4.62,32.0,1.0,0.0,0,0
124,pradipta pramika,T20s,1,1.0,12,24,0,0.00,12.00,0.0,0.0,0.0,0,0
125,ishan porel,First-class,12,18.0,1909,906,32,28.31,2.84,59.6,2.0,2.0,0,0
126,ishan porel,List A,9,9.0,366,296,12,24.66,4.85,30.5,1.0,0.0,0,0
127,prayas ray barman,List A,9,9.0,341,253,11,23.00,4.45,31.0,1.0,0.0,0,0
128,shahbaz ahmed,First-class,2,3.0,180,80,2,40.00,2.66,90.0,0.0,0.0,0,0
129,shahbaz ahmed,List A,6,6.0,210,160,6,26.66,4.57,35.0,0.0,0.0,0,0
130,bandaru ayyappa,First-class,29,48.0,5175,2566,77,33.32,2.97,67.2,3.0,3.0,0,0
131,bandaru ayyappa,List A,31,31.0,1620,1337,43,31.09,4.95,37.6,1.0,0.0,0,0
132,bandaru ayyappa,T20s,26,26.0,557,667,31,21.51,7.18,17.9,0.0,0.0,0,0
133,karthik Raman,First-class,4,6.0,462,255,9,28.33,3.31,51.3,0.0,0.0,0,0
134,karthik Raman,List A,8,8.0,361,313,14,22.35,5.20,25.7,2.0,0.0,0,0
135,karthik Raman,T20s,3,1.0,12,23,0,0.00,11.50,0.0,0.0,0.0,0,0
136,karn sharma,First-class,69,107.0,10155,5381,188,28.62,3.17,54.0,8.0,10.0,1,0
137,karn sharma,List A,80,75.0,3805,3001,99,30.31,4.73,38.4,0.0,2.0,0,0
138,karn sharma,T20s,119,109.0,2027,2483,101,24.58,7.34,20.0,2.0,1.0,0,0
139,Paisikalva Vijaykumar,First-class,69,118.0,14608,5386,239,22.53,2.21,61.1,10.0,10.0,1,0
140,Paisikalva Vijaykumar,List A,28,28.0,1448,1034,34,30.41,4.28,42.5,1.0,0.0,0,0
141,Paisikalva Vijaykumar,T20s,18,18.0,342,466,10,46.60,8.17,34.2,0.0,0.0,0,0
142,Prithvi Raj,First-class,6,11.0,1036,512,21,24.38,2.96,49.3,1.0,0.0,0,0
143,Prithvi Raj,List A,1,1.0,60,65,2,32.50,6.50,30.0,0.0,0.0,0,0

In [4]:
y = dataset.iloc[: , -1]

In [5]:
y

0      1
1      1
2      1
3      0
4      0
5      0
6      1
7      1
8      1
9      1
10     1
11     0
12     0
13     0
14     0
15     0
16     0
17     1
18     1
19     1
20     0
21     0
22     1
23     1
24     1
25     0
26     0
27     0
28     1
29     1
      ..
114    0
115    0
116    1
117    1
118    1
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
Name: capped, Length: 144, dtype: int64

In [6]:
X = dataset.iloc[: , 0:13]

In [7]:
X

,name,mt,Mat,Inns,Balls,Runs,Wkts,Ave,Econ,SR,4w,5w,10
0,Praveen Kumar,First-class,66,121.0,14158,6306,267,23.61,2.67,53.0,16.0,17.0,1
1,Praveen Kumar,List A,139,0.0,6730,5336,185,28.84,4.75,36.3,4.0,2.0,0
2,Praveen Kumar,T20s,177,177.0,3695,4599,143,32.16,7.46,25.8,0.0,0.0,0
3,Akshdeep Nath,First-class,22,12.0,366,179,6,29.83,2.93,61.0,0.0,0.0,0
4,Akshdeep Nath,List A,44,14.0,360,327,13,25.15,5.45,27.6,0.0,0.0,0
5,Akshdeep Nath,T20s,51,15.0,177,241,12,20.08,8.16,14.7,0.0,0.0,0
6,Amit Mishra,First-class,152,0.0,30843,15608,535,29.17,3.03,57.6,0.0,21.0,1
7,Amit Mishra,List A,144,0.0,7426,5681,242,23.47,4.59,30.6,7.0,6.0,0
8,Amit Mishra,T20s,199,198.0,4168,4970,228,21.79,7.15,18.2,4.0,2.0,0
9,Piyush Chawla,First-class,130,227.0,26086,14276,437,32.66,3.28,59.6,22.0,23.0,3
10,Piyush Chawla,List A,131,127.0,6487,5363,208,25.78,4.96,31.1,7.0,3.0,0
11,Piyush Chawla,T20s,208,207.0,4290,5379,218,24.67,7.52,19.6,3.0,0.0,0
12,Mohammad Saif,First-class,17,18.0,451,252,3,84.00,3.35,150.3,0.0,0.0,0
13,Mohammad Saif,List A,5,4.0,150,174,3,58.00,6.96,50.0,0.0,0.0,0
14,Ankit Rajpoot,First-class,50,89.0,9429,4761,174,27.36,3.02,54.1,9.0,8.0,1
15,Ankit Rajpoot,List A,30,29.0,1421,1152,36,32.00,4.86,39.4,0.0,0.0,0
16,Ankit Rajpoot,T20s,54,54.0,1078,1351,68,19.86,7.51,15.8,1.0,2.0,0
17,Kuldeep Yadav,First-class,30,49.0,5774,3512,117,30.01,3.64,49.3,7.0,6.0,0
18,Kuldeep Yadav,List A,45,43.0,2334,1843,83,22.20,4.73,28.1,2.0,2.0,0
19,Kuldeep Yadav,T20s,79,78.0,1695,2073,106,19.55,7.33,15.9,3.0,2.0,0
20,Deependra Pandey,List A,1,1.0,42,36,0,0.00,5.14,0.0,0.0,0.0,0
21,Deependra Pandey,T20s,1,1.0,6,9,0,0.00,9.00,0.0,0.0,0.0,0
22,JaydevUnadkat,First-class,73,125.0,12392,6172,233,26.48,2.98,53.1,11.0,12.0,2
23,JaydevUnadkat,List A,84,84.0,4416,3549,116,30.59,4.82,38.0,5.0,1.0,0
24,JaydevUnadkat,T20s,110,109.0,2331,3054,134,22.79,7.86,17.3,0.0,2.0,0
25,Hardik Rathod,First-class,18,29.0,2942,1508,38,39.68,3.07,77.4,0.0,1.0,0
26,Hardik Rathod,List A,3,3.0,78,76,0,0.00,5.84,0.0,0.0,0.0,0
27,Hardik Rathod,T20s,5,5.0,106,141,2,70.50,7.98,53.0,0.0,0.0,0
28,Dhawal Kulkarni,First-class,86,140.0,15531,7174,261,27.48,2.77,59.5,9.0,15.0,1
29,Dhawal Kulkarni,List A,110,109.0,5461,4308,187,23.03,4.73,29.2,5.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,jayant yadav,T20s,40,36.0,700,695,20,34.75,5.95,35.0,0.0,0.0,0
115,tinu kundu,First-class,4,7.0,799,317,24,13.20,2.38,33.2,1.0,2.0,1
116,ashok dinda,First-class,115,194.0,22866,11823,417,28.35,3.10,54.8,19.0,26.0,5
117,ashok dinda,List A,92,92.0,4686,4015,141,28.47,5.14,33.2,2.0,3.0,0
118,ashok dinda,T20s,133,130.0,2695,3441,132,26.06,7.66,20.4,3.0,0.0,0
119,mukesh kumar,First-class,12,22.0,2170,1045,48,21.77,2.88,45.2,3.0,2.0,0
120,mukesh kumar,List A,8,8.0,384,325,5,65.00,5.07,76.8,0.0,0.0,0
121,mukesh kumar,T20s,6,6.0,126,145,6,24.16,6.90,21.0,0.0,0.0,0
122,pradipta pramika,First-class,7,12.0,1275,614,25,24.56,2.88,51.0,2.0,0.0,0
123,pradipta pramika,List A,8,8.0,384,296,12,24.66,4.62,32.0,1.0,0.0,0
124,pradipta pramika,T20s,1,1.0,12,24,0,0.00,12.00,0.0,0.0,0.0,0
125,ishan porel,First-class,12,18.0,1909,906,32,28.31,2.84,59.6,2.0,2.0,0
126,ishan porel,List A,9,9.0,366,296,12,24.66,4.85,30.5,1.0,0.0,0
127,prayas ray barman,List A,9,9.0,341,253,11,23.00,4.45,31.0,1.0,0.0,0
128,shahbaz ahmed,First-class,2,3.0,180,80,2,40.00,2.66,90.0,0.0,0.0,0
129,shahbaz ahmed,List A,6,6.0,210,160,6,26.66,4.57,35.0,0.0,0.0,0
130,bandaru ayyappa,First-class,29,48.0,5175,2566,77,33.32,2.97,67.2,3.0,3.0,0
131,bandaru ayyappa,List A,31,31.0,1620,1337,43,31.09,4.95,37.6,1.0,0.0,0
132,bandaru ayyappa,T20s,26,26.0,557,667,31,21.51,7.18,17.9,0.0,0.0,0
133,karthik Raman,First-class,4,6.0,462,255,9,28.33,3.31,51.3,0.0,0.0,0
134,karthik Raman,List A,8,8.0,361,313,14,22.35,5.20,25.7,2.0,0.0,0
135,karthik Raman,T20s,3,1.0,12,23,0,0.00,11.50,0.0,0.0,0.0,0
136,karn sharma,First-class,69,107.0,10155,5381,188,28.62,3.17,54.0,8.0,10.0,1
137,karn sharma,List A,80,75.0,3805,3001,99,30.31,4.73,38.4,0.0,2.0,0
138,karn sharma,T20s,119,109.0,2027,2483,101,24.58,7.34,20.0,2.0,1.0,0
139,Paisikalva Vijaykumar,First-class,69,118.0,14608,5386,239,22.53,2.21,61.1,10.0,10.0,1
140,Paisikalva Vijaykumar,List A,28,28.0,1448,1034,34,30.41,4.28,42.5,1.0,0.0,0
141,Paisikalva Vijaykumar,T20s,18,18.0,342,466,10,46.60,8.17,34.2,0.0,0.0,0
142,Prithvi Raj,First-class,6,11.0,1036,512,21,24.38,2.96,49.3,1.0,0.0,0
143,Prithvi Raj,List A,1,1.0,60,65,2,32.50,6.50,30.0,0.0,0.0,0

In [8]:
name = dataset.iloc[: ,0 ]

name

In [9]:
mt = X.iloc[:,1]
mt

0      First-class
1           List A
2             T20s
3      First-class
4           List A
5             T20s
6      First-class
7           List A
8             T20s
9      First-class
10          List A
11            T20s
12     First-class
13          List A
14     First-class
15          List A
16            T20s
17     First-class
18          List A
19            T20s
20          List A
21            T20s
22     First-class
23          List A
24            T20s
25     First-class
26          List A
27            T20s
28     First-class
29          List A
          ...
114           T20s
115    First-class
116    First-class
117         List A
118           T20s
119    First-class
120         List A
121           T20s
122    First-class
123         List A
124           T20s
125    First-class
126         List A
127         List A
128    First-class
129         List A
130    First-class
131         List A
132           T20s
133    First-class
134         List A
135           T20s
136    First-class
137         List A
138           T20s
139    First-class
140         List A
141           T20s
142    First-class
143         List A
Name: mt, Length: 144, dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
mt_new = labelencoder_x.fit_transform(mt)
X.iloc[:,1]= mt_new

In [11]:
# preprocess :  categorical variable
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
name_new = labelencoder_x.fit_transform(name)
X.iloc[:,0]=name_new

In [12]:
X

,name,mt,Mat,Inns,Balls,Runs,Wkts,Ave,Econ,SR,4w,5w,10
0,19,0,66,121.0,14158,6306,267,23.61,2.67,53.0,16.0,17.0,1
1,19,1,139,0.0,6730,5336,185,28.84,4.75,36.3,4.0,2.0,0
2,19,2,177,177.0,3695,4599,143,32.16,7.46,25.8,0.0,0.0,0
3,0,0,22,12.0,366,179,6,29.83,2.93,61.0,0.0,0.0,0
4,0,1,44,14.0,360,327,13,25.15,5.45,27.6,0.0,0.0,0
5,0,2,51,15.0,177,241,12,20.08,8.16,14.7,0.0,0.0,0
6,1,0,152,0.0,30843,15608,535,29.17,3.03,57.6,0.0,21.0,1
7,1,1,144,0.0,7426,5681,242,23.47,4.59,30.6,7.0,6.0,0
8,1,2,199,198.0,4168,4970,228,21.79,7.15,18.2,4.0,2.0,0
9,17,0,130,227.0,26086,14276,437,32.66,3.28,59.6,22.0,23.0,3
10,17,1,131,127.0,6487,5363,208,25.78,4.96,31.1,7.0,3.0,0
11,17,2,208,207.0,4290,5379,218,24.67,7.52,19.6,3.0,0.0,0
12,14,0,17,18.0,451,252,3,84.00,3.35,150.3,0.0,0.0,0
13,14,1,5,4.0,150,174,3,58.00,6.96,50.0,0.0,0.0,0
14,2,0,50,89.0,9429,4761,174,27.36,3.02,54.1,9.0,8.0,1
15,2,1,30,29.0,1421,1152,36,32.00,4.86,39.4,0.0,0.0,0
16,2,2,54,54.0,1078,1351,68,19.86,7.51,15.8,1.0,2.0,0
17,12,0,30,49.0,5774,3512,117,30.01,3.64,49.3,7.0,6.0,0
18,12,1,45,43.0,2334,1843,83,22.20,4.73,28.1,2.0,2.0,0
19,12,2,79,78.0,1695,2073,106,19.55,7.33,15.9,3.0,2.0,0
20,3,1,1,1.0,42,36,0,0.00,5.14,0.0,0.0,0.0,0
21,3,2,1,1.0,6,9,0,0.00,9.00,0.0,0.0,0.0,0
22,10,0,73,125.0,12392,6172,233,26.48,2.98,53.1,11.0,12.0,2
23,10,1,84,84.0,4416,3549,116,30.59,4.82,38.0,5.0,1.0,0
24,10,2,110,109.0,2331,3054,134,22.79,7.86,17.3,0.0,2.0,0
25,6,0,18,29.0,2942,1508,38,39.68,3.07,77.4,0.0,1.0,0
26,6,1,3,3.0,78,76,0,0.00,5.84,0.0,0.0,0.0,0
27,6,2,5,5.0,106,141,2,70.50,7.98,53.0,0.0,0.0,0
28,4,0,86,140.0,15531,7174,261,27.48,2.77,59.5,9.0,15.0,1
29,4,1,110,109.0,5461,4308,187,23.03,4.73,29.2,5.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,39,2,40,36.0,700,695,20,34.75,5.95,35.0,0.0,0.0,0
115,48,0,4,7.0,799,317,24,13.20,2.38,33.2,1.0,2.0,1
116,33,0,115,194.0,22866,11823,417,28.35,3.10,54.8,19.0,26.0,5
117,33,1,92,92.0,4686,4015,141,28.47,5.14,33.2,2.0,3.0,0
118,33,2,133,130.0,2695,3441,132,26.06,7.66,20.4,3.0,0.0,0
119,43,0,12,22.0,2170,1045,48,21.77,2.88,45.2,3.0,2.0,0
120,43,1,8,8.0,384,325,5,65.00,5.07,76.8,0.0,0.0,0
121,43,2,6,6.0,126,145,6,24.16,6.90,21.0,0.0,0.0,0
122,44,0,7,12.0,1275,614,25,24.56,2.88,51.0,2.0,0.0,0
123,44,1,8,8.0,384,296,12,24.66,4.62,32.0,1.0,0.0,0
124,44,2,1,1.0,12,24,0,0.00,12.00,0.0,0.0,0.0,0
125,37,0,12,18.0,1909,906,32,28.31,2.84,59.6,2.0,2.0,0
126,37,1,9,9.0,366,296,12,24.66,4.85,30.5,1.0,0.0,0
127,45,1,9,9.0,341,253,11,23.00,4.45,31.0,1.0,0.0,0
128,47,0,2,3.0,180,80,2,40.00,2.66,90.0,0.0,0.0,0
129,47,1,6,6.0,210,160,6,26.66,4.57,35.0,0.0,0.0,0
130,34,0,29,48.0,5175,2566,77,33.32,2.97,67.2,3.0,3.0,0
131,34,1,31,31.0,1620,1337,43,31.09,4.95,37.6,1.0,0.0,0
132,34,2,26,26.0,557,667,31,21.51,7.18,17.9,0.0,0.0,0
133,41,0,4,6.0,462,255,9,28.33,3.31,51.3,0.0,0.0,0
134,41,1,8,8.0,361,313,14,22.35,5.20,25.7,2.0,0.0,0
135,41,2,3,1.0,12,23,0,0.00,11.50,0.0,0.0,0.0,0
136,40,0,69,107.0,10155,5381,188,28.62,3.17,54.0,8.0,10.0,1
137,40,1,80,75.0,3805,3001,99,30.31,4.73,38.4,0.0,2.0,0
138,40,2,119,109.0,2027,2483,101,24.58,7.34,20.0,2.0,1.0,0
139,16,0,69,118.0,14608,5386,239,22.53,2.21,61.1,10.0,10.0,1
140,16,1,28,28.0,1448,1034,34,30.41,4.28,42.5,1.0,0.0,0
141,16,2,18,18.0,342,466,10,46.60,8.17,34.2,0.0,0.0,0
142,20,0,6,11.0,1036,512,21,24.38,2.96,49.3,1.0,0.0,0
143,20,1,1,1.0,60,65,2,32.50,6.50,30.0,0.0,0.0,0

In [13]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()

In [14]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [15]:
dataset.iloc[:,1]=mt_new 
mt_new

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1], dtype=int64)

In [16]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder( categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [17]:
X

array([[ 1.,  0.,  1., ..., 16., 17.,  1.],
       [ 1.,  0.,  1., ...,  4.,  2.,  0.],
       [ 1.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 1.,  0.,  1., ...,  0.,  0.,  0.],
       [ 1.,  0.,  1., ...,  1.,  0.,  0.],
       [ 1.,  0.,  1., ...,  0.,  0.,  0.]])

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [20]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [21]:
model.fit(X_train ,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [22]:
model.predict(X_test)

array([ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.99040784e-12,  2.36166642e-12,  4.85918310e-01,
        4.85918310e-01,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.57429625e-12, -1.56796798e-12,  6.48703313e-13,  4.85918310e-01,
        1.53010937e-12,  1.00000000e+00,  8.69637695e-13,  1.00000000e+00,
        1.00000000e+00,  3.04978265e-13,  1.00000000e+00,  1.70075065e-12,
        1.00000000e+00,  1.51134660e-12,  1.00000000e+00,  4.37871961e-13,
        1.62525549e-12])

In [23]:
y_test

117    1
19     1
82     1
97     1
56     1
12     0
132    0
65     1
66     1
18     1
51     1
78     1
94     0
133    0
100    0
64     1
27     0
69     1
125    0
73     1
11     0
119    0
110    1
113    0
55     1
45     0
9      1
4      0
26     0
Name: capped, dtype: int64